### ISSUE TITLE
Cannot Query - AttributeError

### ISSUE THREAD

**Issue by sfog17** [cloudflare/sqlalchemy-clickhouse#22]
When I try to return the table names or execute a query, I get an error
(this is with the sql alchemy version 1.2.7)

**Code**
> import sqlalchemy as sa
>engine = sa.create_engine('clickhouse://localhost:8123/')
>engine.table_names()

**Issue**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2139, in table_names
    return self.dialect.get_table_names(conn, schema)
  File "<string>", line 2, in get_table_names
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 42, in cache
    return fn(self, con, *args, **kw)
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy_clickhouse-0.1.3.post0-py3.6.egg/sqlalchemy_clickhouse/base.py", line 285, in get_table_names
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 942, in execute
    return self._execute_text(object, multiparams, params)
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1104, in _execute_text
    statement, parameters
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1416, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy_clickhouse-0.1.3.post0-py3.6.egg/sqlalchemy_clickhouse/connector.py", line 209, in execute
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy_clickhouse-0.1.3.post0-py3.6.egg/sqlalchemy_clickhouse/connector.py", line 342, in _process_response
  File "/home/<user>/anaconda3/lib/python3.6/site-packages/sqlalchemy_clickhouse-0.1.3.post0-py3.6.egg/sqlalchemy_clickhouse/connector.py", line 342, in <listcomp>
AttributeError: 'str' object has no attribute 'db_type'
```

**Comment by blackmagic02881** [comment]
got same issue when tried to create a table

**Comment by Boiler** [comment]
same problem

**Comment by fyzbt** [comment]
it's the same for 1.2.10. And even for the latest version built from https://github.com/JustOnce/sqlalchemy-clickhouse. Has anybody solved the problem?

**Comment by inpefess** [comment]
The problem is solved by a PR that I submitted today: https://github.com/cloudflare/sqlalchemy-clickhouse/pull/24

**Comment by vavrusa** [comment]
I uploaded a new PyPi with #24 (0.1.4.post0)
