### ISSUE TITLE
Authorization is broken?

### ISSUE THREAD

**Issue by pkesso** [cloudflare/sqlalchemy-clickhouse#49]
sqlalchemy-clickhouse version: 0.1.5.post0 from pypi
clickhouse version: 19.13.2.19

Trying to connect:
```(venv) [user@srv1:~/venv]$ python
Python 3.6.8 (default, Apr 25 2019, 21:02:35) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy
>>> engine = sqlalchemy.create_engine('clickhouse://test:pUK4Tyk4GMVvn4cG@127.0.0.1:8123/metrics')
>>> result = engine.execute("select * from test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2178, in execute
    connection = self._contextual_connect(close_with_result=True)
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2239, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy_clickhouse/connector.py", line 111, in connect
    return Connection(*args, **kwargs)
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy_clickhouse/connector.py", line 118, in __init__
    super(Connection, self).__init__(db_name, db_url, username, password, readonly)
  File "/home/pkesso/venv/lib/python3.6/site-packages/infi/clickhouse_orm/database.py", line 112, in __init__
    self.db_exists = self._is_existing_database()
  File "/home/pkesso/venv/lib/python3.6/site-packages/infi/clickhouse_orm/database.py", line 393, in _is_existing_database
    r = self._send("SELECT count() FROM system.databases WHERE name = '%s'" % self.db_name)
  File "/home/pkesso/venv/lib/python3.6/site-packages/sqlalchemy_clickhouse/connector.py", line 102, in _send
    raise Exception(r.text)
Exception: Code: 194, e.displayText() = DB::Exception: Password required for user default (version 19.13.2.19)
```
clickhouse log:

`2019.09.24 12:58:41.979196 [ 56 ] {} <Error> HTTPHandler: Code: 194, e.displayText() = DB::Exception: Password required for user default, Stack trace:`

As you can see, I tried to connect with 'test' user and some password, but it seems to ignore user and password. The only situation where I was able to conntect is default user with no password.

**Comment by adaiboy** [comment]
comment(disable) the code Database._send = _send in sqlalchemy_clickhouse/connector.py
as it will use none auth to check _is_existing_database in infi/clickhouse_orm/database.py

**Comment by healiseu** [comment]
Thanks @adaiboy I confirm that the patch is working with ClickHouse version 19.15.3.6

**Comment by vavrusa** [comment]
Is this working after https://github.com/cloudflare/sqlalchemy-clickhouse/pull/55 ?

**Comment by naoko** [comment]
No even after #55, not working for me but works with `infi.clickhouse-orm to version 1.0.3.`
