### ISSUE TITLE
works wrong for specific clickhouse type  LowCardinality(String)

### ISSUE THREAD

**Issue by zhougit86** [cloudflare/sqlalchemy-clickhouse#58]
2020-04-22 13:57:31,804:ERROR:root:No field class for LowCardinality(String)
Traceback (most recent call last):
  File "/root/superset/venv/lib/python2.7/site-packages/superset/sql_lab.py", line 179, in execute_sql
    **db_engine_spec.cursor_execute_kwargs)
  File "/root/superset/venv/lib/python2.7/site-packages/sqlalchemy_clickhouse/connector.py", line 210, in execute
    self._process_response(response)
  File "/root/superset/venv/lib/python2.7/site-packages/sqlalchemy_clickhouse/connector.py", line 341, in _process_response
    for r in response:
  File "/root/superset/venv/lib/python2.7/site-packages/infi/clickhouse_orm/database.py", line 244, in select
    model_class = model_class or ModelBase.create_ad_hoc_model(zip(field_names, field_types))
  File "/root/superset/venv/lib/python2.7/site-packages/infi/clickhouse_orm/models.py", line 59, in create_ad_hoc_model
    attrs[name] = cls.create_ad_hoc_field(db_type)
  File "/root/superset/venv/lib/python2.7/site-packages/sqlalchemy_clickhouse/connector.py", line 75, in create_ad_hoc_field
    inner_field = cls.create_ad_hoc_field(db_type[6 : -1])
  File "/root/superset/venv/lib/python2.7/site-packages/sqlalchemy_clickhouse/connector.py", line 91, in create_ad_hoc_field
    raise NotImplementedError('No field class for %s' % db_type)

**Comment by zhougit86** [comment]
@vavrusa

**Comment by jackpgao** [comment]
用最新版，直接下载master分支，python setup.py install
作者一直没有往pypi更新，pip安装的不是最新的

**Comment by hyberdk** [comment]
yup it worked for me also, copying in the latest master branch and replace the files in the pip package did the trick.. Thanks jackpgao.

@cloudflare, can you please update the pip package..

**Comment by vavrusa** [comment]
Sorry, I've been busy. I'll wait a bit for https://github.com/cloudflare/sqlalchemy-clickhouse/pull/47 and update pip package.

**Comment by Ernestyj** [comment]
seems the #47 is done. Could we update the pip package?

**Comment by uSasha** [comment]
For everyone waiting for pip package: `pip install git+https://github.com/cloudflare/sqlalchemy-clickhouse.git ` will work.

**Comment by naoko** [comment]
`LowCardinality` can have `FixedString(N)` too. Would it be safe to say if db_type contains `FixedString` then `String`?

**Comment by Shardy153** [comment]
> For everyone waiting for pip package: `pip install git+https://github.com/cloudflare/sqlalchemy-clickhouse.git ` will work.

I have put git+https://github.com/cloudflare/sqlalchemy-clickhouse.git in my requirements.txt file but still getting this exception.
Can you help me?

**Comment by badihi** [comment]
I can see that the problem still exists for columns of type `LowCardinality(Nullable(String))` using the code on `mater` right now.
