### ISSUE TITLE
password is incorrect or there is no user with such name

### ISSUE THREAD

**Issue by Michaelsky0913** [cloudflare/sqlalchemy-clickhouse#77]
After I create a clickhouse engine, I want to execute a simple query like 'select 1'. It reminds me that password is incorrect or there is no user with such name.
In fact, the user and password is correct.
Here is the code that I created for connect my clickhouse-server:
```
import sqlalchemy as sa
engine = sa.create_engine('clickhouse://default:123qwe@192.168.13.251:8123/dbtest')
```
![image](https://user-images.githubusercontent.com/40595864/115200855-3fbbc980-a127-11eb-8fbe-d38cbbdf17e5.png)

then I use engine to execute a simple query:
```
engine.execute('select 1')
```
>>> engine.execute('select 1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2234, in execute
    connection = self._contextual_connect(close_with_result=True)
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy_clickhouse/connector.py", line 111, in connect
    return Connection(*args, **kwargs)
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy_clickhouse/connector.py", line 118, in __init__
    super(Connection, self).__init__(db_name, db_url, username, password, readonly)
  File "/opt/venv4superset/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 111, in __init__
    self.db_exists = self._is_existing_database()
  File "/opt/venv4superset/lib/python3.8/site-packages/infi/clickhouse_orm/database.py", line 414, in _is_existing_database
    r = self._send("SELECT count() FROM system.databases WHERE name = '%s'" % self.db_name)
  File "/opt/venv4superset/lib/python3.8/site-packages/sqlalchemy_clickhouse/connector.py", line 102, in _send
    raise Exception(r.text)
Exception: Code: 516, e.displayText() = DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name (version 21.3.4.25 (official build))

After that, I use linux command to test the connect:
```
echo 'SELECT 1' | curl 'http://192.168.13.251:8123/' -udefault:123qwe --data-binary @-
```
there is ok.
![image](https://user-images.githubusercontent.com/40595864/115201216-a7721480-a127-11eb-904b-5bf4294548ea.png)
the password of user default config:
![image](https://user-images.githubusercontent.com/40595864/115204228-d5a52380-a12a-11eb-9e8b-8d5cb20868b9.png)

if I don't set password for user default, everything is ok.
![image](https://user-images.githubusercontent.com/40595864/115204321-f1102e80-a12a-11eb-95ce-f769eb815766.png)
![image](https://user-images.githubusercontent.com/40595864/115204530-2a489e80-a12b-11eb-901b-ad887c36804c.png)

if I setted, everything is not ok.
![image](https://user-images.githubusercontent.com/40595864/115204645-4fd5a800-a12b-11eb-8c71-967857a9448e.png)
![image](https://user-images.githubusercontent.com/40595864/115204746-68de5900-a12b-11eb-8051-fce46f44697b.png)

even I use other user with no password, it also not ok.
![image](https://user-images.githubusercontent.com/40595864/115204924-9cb97e80-a12b-11eb-8668-a06069063efd.png)
![image](https://user-images.githubusercontent.com/40595864/115204970-a93dd700-a12b-11eb-8fbb-cfa7722de150.png)

it told me that default user's password is incorrect.(I use the dev_ro user to connect to the server....)
![image](https://user-images.githubusercontent.com/40595864/115205548-426ced80-a12c-11eb-8747-d15f23f8422e.png)

**Comment by wwwDengJXcom** [comment]
I also have the same problem, as long as the password is set, I can not connect

**Comment by Michaelsky0913** [comment]
@wwwDengJXcom you can use clickhouse-sqlalchemy instead of use sqlalchemy-clickhouse
